version: '3.8'

services:
  mediamarkt-app:
    container_name: mediamarkt-app
    build: .
    ports:
      - "8080:8080"
    environment:
      spring.application.name: mediamarkt
      server.port: 8080
      data.source.driver-class-name: org.postgresql.Driver
      spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
      spring.datasource.username: postgres
      spring.datasource.password: 19111993
      spring.datasource.url: jdbc:postgresql://postgres:5432/mediamarkt
      spring.jpa.show-sql: "true"
      spring.jpa.hibernate.ddl-auto: update
      spring.data.redis.host: redis
      spring.data.redis.port: 6379
    depends_on:
      - redis
      - postgres

  postgres:
    container_name: mediamarkt-postgres
    image: postgres
    environment:
      POSTGRES_DB: mediamarkt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19111993
    ports:
      - "5432:5432"

  redis:
    container_name: mediamarkt-redis
    image: redis
    ports:
      - "6379:6379"
