version: '3.8'

services:
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: mediamarkt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19111993
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: mediamarkt
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/mediamarkt
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 19111993
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres-db
      - redis

volumes:
  postgres_data:
