#spring:
#  redis:
#    host: mediamarkt-redis-1 # Имя хоста контейнера Redis
#    port: 6379 # Порт Redis
#
#  datasource:
#    url: jdbc:postgresql://mediamarkt-postgres-db-1:5432/mediamarkt # URL для подключения к базе данных PostgreSQL
#    username: myusername # Имя пользователя базы данных PostgreSQL
#    password: mypassword # Пароль пользователя базы данных PostgreSQL
#    driver-class-name: org.postgresql.Driver # Драйвер JDBC для PostgreSQL
