INSERT INTO category (name) VALUES
                                ('Мобильные телефоны'),
                                ('Ноутбуки'),
                                ('Бытовая техника'),
                                ('Аксессуары'),
                                ('Электроинструменты'),
                                ('Светотехника'),
                                ('Кабельная продукция'),
                                ('Розетки и выключатели'),
                                ('Электрические плиты и духовки'),
                                ('Климатическая техника'),
                                ('Умный дом'),
                                ('Батареи и аккумуляторы');



-- Assuming category_id from 1 to 12 matches the inserted categories above.
INSERT INTO product (name, description, price, image_url, category_id, stock_quantity) VALUES
                                                                                         ('iPhone 12', 'Новейший iPhone с улучшенной камерой', 799.99, 'url_to_image_1', 1, 50),
                                                                                         ('Samsung Galaxy S21', 'Флагманский телефон от Samsung', 699.99, 'url_to_image_2', 1, 30),
                                                                                         ('MacBook Pro', 'Мощный ноутбук от Apple', 1299.99, 'url_to_image_3', 2, 20),
                                                                                         ('Dell XPS 13', 'Легкий и мощный ноутбук от Dell', 999.99, 'url_to_image_4', 2, 25),
                                                                                         ('Dyson V11', 'Пылесос для уборки дома', 499.99, 'url_to_image_5', 3, 15),
                                                                                         ('Sony WH-1000XM4', 'Беспроводные наушники с шумоподавлением', 349.99, 'url_to_image_6', 4, 40),
                                                                                         ('Bosch Drill', 'Мощная дрель для дома и работы', 149.99, 'url_to_image_7', 5, 10),
                                                                                         ('Philips Hue', 'Умная лампа с управлением через смартфон', 59.99, 'url_to_image_8', 6, 100),
                                                                                         ('HDMI Cable', 'Кабель HDMI высокого качества', 19.99, 'url_to_image_9', 7, 200),
                                                                                         ('Smart Plug', 'Умная розетка с Wi-Fi управлением', 29.99, 'url_to_image_10', 8, 150),
                                                                                         ('Electric Oven', 'Электрическая духовка для дома', 299.99, 'url_to_image_11', 9, 5),
                                                                                         ('Portable Air Conditioner', 'Портативный кондиционер для дома', 399.99, 'url_to_image_12', 10, 8),
                                                                                         ('Smart Thermostat', 'Умный термостат для дома', 199.99, 'url_to_image_13', 11, 12),
                                                                                         ('Rechargeable Batteries', 'Перезаряжаемые батареи для устройств', 29.99, 'url_to_image_14', 12, 300),
                                                                                         ('Wireless Charger', 'Беспроводное зарядное устройство для смартфонов', 49.99, 'url_to_image_15', 4, 70),
                                                                                         ('Bluetooth Speaker', 'Беспроводная колонка с Bluetooth', 99.99, 'url_to_image_16', 4, 45),
                                                                                         ('Laptop Bag', 'Сумка для ноутбука с защитой', 39.99, 'url_to_image_17', 4, 80),
                                                                                         ('Robot Vacuum', 'Робот-пылесос для уборки дома', 299.99, 'url_to_image_18', 3, 20),
                                                                                         ('Gaming Mouse', 'Игровая мышь с подсветкой', 59.99, 'url_to_image_19', 4, 60),
                                                                                         ('Smart Light Switch', 'Умный выключатель света с Wi-Fi', 39.99, 'url_to_image_20', 8, 90),
                                                                                         ('Electric Kettle', 'Электрический чайник для дома', 49.99, 'url_to_image_21', 3, 25),
                                                                                         ('Wireless Earbuds', 'Беспроводные наушники с зарядным кейсом', 149.99, 'url_to_image_22', 4, 55),
                                                                                         ('Fitness Tracker', 'Фитнес-трекер с мониторингом здоровья', 79.99, 'url_to_image_23', 4, 100),
                                                                                         ('Smart Doorbell', 'Умный дверной звонок с камерой', 99.99, 'url_to_image_24', 11, 30),
                                                                                         ('Cordless Drill', 'Аккумуляторная дрель для работы', 129.99, 'url_to_image_25', 5, 15),
                                                                                         ('Electric Heater', 'Электрический обогреватель для дома', 89.99, 'url_to_image_26', 10, 12),
                                                                                         ('Portable Power Bank', 'Портативный аккумулятор для устройств', 39.99, 'url_to_image_27', 12, 120),
                                                                                         ('Smartwatch', 'Умные часы с мониторингом активности', 199.99, 'url_to_image_28', 4, 35),
                                                                                         ('Digital Camera', 'Цифровая камера для фотографий', 499.99, 'url_to_image_29', 4, 10),
                                                                                         ('Wireless Keyboard', 'Беспроводная клавиатура для компьютера', 59.99, 'url_to_image_30', 4, 65);


INSERT INTO product (name, description, price, image_url, category_id, stock_quantity) VALUES
                                                                                           ('Smart TV 4K', 'Умный телевизор с поддержкой 4K', 899.99, 'url_to_image_31', 7, 25),
                                                                                           ('AirPods Pro', 'Беспроводные наушники с функцией активного шумоподавления', 249.99, 'url_to_image_32', 4, 50),
                                                                                           ('Coffee Maker', 'Кофеварка для приготовления вкусного кофе', 79.99, 'url_to_image_33', 9, 15),
                                                                                           ('Electric Scooter', 'Электрический скутер для городских поездок', 399.99, 'url_to_image_34', 10, 10),
                                                                                           ('VR Headset', 'Виртуальная реальность для игр и развлечений', 299.99, 'url_to_image_35', 11, 20),
                                                                                           ('Kindle Paperwhite', 'Электронная книга с подсветкой и высоким разрешением', 149.99, 'url_to_image_36', 12, 30),
                                                                                           ('Portable Monitor', 'Портативный монитор для работы и игр', 199.99, 'url_to_image_37', 2, 15),
                                                                                           ('Digital Drawing Tablet', 'Цифровая графическая планшетка для художников', 129.99, 'url_to_image_38', 4, 25),
                                                                                           ('WiFi Router', 'Беспроводный маршрутизатор для домашней сети', 69.99, 'url_to_image_39', 8, 40),
                                                                                           ('External Hard Drive', 'Внешний жесткий диск для хранения данных', 129.99, 'url_to_image_40', 9, 50),
                                                                                           ('Bluetooth Earphones', 'Беспроводные наушники с Bluetooth для спорта', 39.99, 'url_to_image_41', 4, 80),
                                                                                           ('Robot Lawn Mower', 'Робот для стрижки газона', 599.99, 'url_to_image_42', 3, 5),
                                                                                           ('Smart Scale', 'Умные весы с анализом состава тела', 49.99, 'url_to_image_43', 11, 60),
                                                                                           ('Electric Toothbrush', 'Электрическая зубная щетка с таймером', 79.99, 'url_to_image_44', 12, 40),
                                                                                           ('Standing Desk', 'Стол для работы стоя', 299.99, 'url_to_image_45', 2, 15),
                                                                                           ('Noise-Canceling Earbuds', 'Наушники с активным шумоподавлением для музыки и звонков', 149.99, 'url_to_image_46', 4, 30),
                                                                                           ('Digital Photo Frame', 'Цифровая фоторамка для отображения фотографий', 89.99, 'url_to_image_47', 9, 25),
                                                                                           ('Smart Coffee Machine', 'Умная кофеварка с настройкой через приложение', 199.99, 'url_to_image_48', 9, 20),
                                                                                           ('Wireless Security Camera', 'Беспроводная камера для видеонаблюдения', 129.99, 'url_to_image_49', 11, 35),
                                                                                           ('Electric Skateboard', 'Электрический скейтборд для городских перемещений', 299.99, 'url_to_image_50', 10, 8),
                                                                                           ('Mini Projector', 'Мини-проектор для просмотра фильмов и презентаций', 149.99, 'url_to_image_51', 7, 15),
                                                                                           ('Smart Lock', 'Умный замок для дверей с Wi-Fi подключением', 199.99, 'url_to_image_52', 11, 25),
                                                                                           ('Portable Blender', 'Портативный блендер для приготовления смузи', 49.99, 'url_to_image_53', 9, 30),
                                                                                           ('Cordless Vacuum Cleaner', 'Аккумуляторный пылесос для уборки дома', 179.99, 'url_to_image_54', 3, 20),
                                                                                           ('Wireless Gaming Headset', 'Беспроводные игровые наушники с микрофоном', 129.99, 'url_to_image_55', 4, 40),
                                                                                           ('Smart Kitchen Scale', 'Умные кухонные весы для точного взвешивания', 59.99, 'url_to_image_56', 9, 50),
                                                                                           ('Air Fryer', 'Воздушная жаровня для быстрого приготовления блюд', 99.99, 'url_to_image_57', 9, 25),
                                                                                           ('Electric Scooter for Kids', 'Электрический скутер для детей', 199.99, 'url_to_image_58', 10, 10),
                                                                                           ('Smart Mirror', 'Умное зеркало с встроенным дисплеем и Wi-Fi', 299.99, 'url_to_image_59', 11, 15),
                                                                                           ('Bluetooth Keyboard', 'Клавиатура с Bluetooth для планшетов и смартфонов', 49.99, 'url_to_image_60', 8, 20),
                                                                                           ('UV Sterilizer Box', 'УФ стерилизатор для мобильных устройств и масок', 79.99, 'url_to_image_61', 12, 30),
                                                                                           ('Smart Water Bottle', 'Умная бутылка с напоминаниями о питье воды', 29.99, 'url_to_image_62', 9, 100),
                                                                                           ('Wireless Presenter', 'Беспроводной пульт для презентаций', 39.99, 'url_to_image_63', 7, 50),
                                                                                           ('Mini Air Purifier', 'Мини-очиститель воздуха для офиса и дома', 59.99, 'url_to_image_64', 10, 30),
                                                                                           ('Portable Espresso Maker', 'Портативная кофеварка для любителей кофе', 69.99, 'url_to_image_65', 9, 25),
                                                                                           ('Gaming Chair', 'Игровое кресло для комфортного игрового опыта', 199.99, 'url_to_image_66', 7, 20),
                                                                                           ('Smart Ceiling Fan', 'Умный потолочный вентилятор с Wi-Fi управлением', 149.99, 'url_to_image_67', 11, 15),
                                                                                           ('Portable Ice Maker', 'Портативный льдогенератор для вечеринок и дачи', 129.99, 'url_to_image_68', 9, 10),
                                                                                           ('Electric Wine Opener', 'Электрический открывалка для вина', 29.99, 'url_to_image_69', 12, 50),
                                                                                           ('Wireless Charging Pad', 'Беспроводная зарядная платформа для смартфонов', 19.99, 'url_to_image_70', 8, 150),
                                                                                           ('Digital Voice Recorder', 'Цифровой диктофон для записи звука', 49.99, 'url_to_image_71', 7, 50),
                                                                                           ('Smart Home Hub', 'Умный центр для управления умным домом', 99.99, 'url_to_image_72', 11, 20),
                                                                                           ('Video Doorbell', 'Видеодверной звонок с записью и Wi-Fi', 149.99, 'url_to_image_73', 11, 25),
                                                                                           ('Electric Pressure Cooker', 'Мультиварка с функцией быстрого приготовления', 79.99, 'url_to_image_74', 9, 30),
                                                                                           ('Portable Monitor Stand', 'Портативная подставка для монитора', 29.99, 'url_to_image_75', 2, 50),
                                                                                           ('Wireless Meat Thermometer', 'Беспроводной мясной термометр для кухни', 39.99, 'url_to_image_76', 9, 40),
                                                                                           ('Solar Power Bank', 'Солнечный портативный аккумулятор для зарядки', 49.99, 'url_to_image_77', 12, 30),
                                                                                           ('Adjustable Laptop Stand', 'Регулируемая подставка для ноутбука', 39.99, 'url_to_image_78', 2, 40),
                                                                                           ('Smart Foot Massager', 'Умный массажер для стоп с функцией обогрева', 99.99, 'url_to_image_79', 11, 15),
                                                                                           ('Electric Blanket', 'Электрическое одеяло с разогревом', 79.99, 'url_to_image_80', 10, 20);
